'use strict';

angular.module('constant', [])
  .constant('AppInfo', new function(){
    var isProduction = false;
    var version = 'v1.0.9';
    var appname = 'hanasee'; //appname => 유저관리, 앱관리 등에 공통으로 사용. 수정 신중히
    return {
      'isProduction' : isProduction,
      'version' : version,
      'appname': appname,
      'title': '',
      'webUrl': 'http://'+appname+'.com',
      'imagePath': '/images',
      'mailto': 'mailto:nuts@jumpingnuts.com',
      'company': 'Jumping Nuts Inc.',
      'establishmentYear': new Date().getFullYear(),
      'api' : {
        'baseUrl': isProduction ? 'http://api.jumpingnuts.com' : 'http://localhost:8080', //개발
//        'baseUrl': 'http://127.0.0.1:9002/dummy', //개발
        'clientId': '0441c0011f37fec037843fcfe314366f',
        'responseType': 'token',
        'openType': 'iframe'//iframe, opener
      },
      'android': {
        'appId': 'com.jumpingnuts.'+appname,
        'url' : 'https://play.google.com/store/apps/details?id='+'com.jumpingnuts.'+appname,
        'urlCustom' : 'market://details?id='+'com.jumpingnuts.'+appname
      },
      'currentBrowser': {
        'isAndroid' : window.navigator.userAgent.toLowerCase().search('android') > -1,
        'isInApp': window.android ? true : false
      },
      'snsKey': {
        'fb': '264001293758406'
      }
    }
  })

  .constant('SupportLanguage', {
    'ko': {'name':'한국어', 'defaultCountry':'kr'},
    'en': {'name':'English', 'defaultCountry':'us'},
    'ja': {'name':'日本語', 'defaultCountry':'jp'}
  })

  .constant('SupportCountry', {
    "kr":{"name":"대한민국"},
    "us":{"name":"United States"},
    "jp":{"name":"日本"},
    "af":{"name":"افغانستان"},
    "ax":{"name":"Åland Islands"},
    "al":{"name":"Shqipëria"},
    "dz":{"name":"الجزائر"},
    "as":{"name":"Amerika Sāmoa"},
    "ad":{"name":"Andorra"},
    "ao":{"name":"Angola"},
    "ai":{"name":"Anguilla"},
    "aq":{"name":"Antarctica"},
    "ag":{"name":"Antigua and Barbuda"},
    "ar":{"name":"Argentina"},
    "am":{"name":"Հայաստան"},
    "aw":{"name":"Aruba"},
    "au":{"name":"Australia"},
    "at":{"name":"Österreich"},
    "az":{"name":"Azərbaycan"},
    "bs":{"name":"The Bahamas"},
    "bh":{"name":"البحرين"},
    "bd":{"name":"বাংলাদেশ"},
    "bb":{"name":"Barbados"},
    "by":{"name":"Беларусь"},
    "be":{"name":"België"},
    "bz":{"name":"Belize"},
    "bj":{"name":"Bénin"},
    "bm":{"name":"Bermuda"},
    "bt":{"name":"འབྲུག་ཡུལ"},
    "bo":{"name":"Bolivia"},
    "bq":{"name":"Bonaire, Sint Eustatius and Saba"},
    "ba":{"name":"Босна и Херцеговина"},
    "bw":{"name":"Botswana"},
    "bv":{"name":"Bouvet Island"},
    "br":{"name":"Brasil"},
    "io":{"name":"British Indian Ocean Territory"},
    "bn":{"name":"بروني"},
    "bg":{"name":"България"},
    "bf":{"name":"Burkina Faso"},
    "bi":{"name":"Burundi"},
    "kh":{"name":"កម្ពុជា"},
    "cm":{"name":"Cameroun"},
    "ca":{"name":"Canada"},
    "cv":{"name":"Cabo Verde"},
    "ky":{"name":"Cayman Islands"},
    "cf":{"name":"République Centrafricaine"},
    "td":{"name":"تشاد"},
    "cl":{"name":"Chile"},
    "cn":{"name":"中华人民共和国"},
    "cx":{"name":"Christmas Island"},
    "cc":{"name":"Cocos (Keeling) Islands"},
    "co":{"name":"Colombia"},
    "km":{"name":"Komori"},
    "cg":{"name":"République démocratique du Congo"},
    "cd":{"name":"République du Congo"},
    "ck":{"name":"Cook Islands"},
    "cr":{"name":"Costa Rica"},
    "ci":{"name":"Côte d'Ivoire"},
    "hr":{"name":"Hrvatska"},
    "cu":{"name":"Cuba"},
    "cw":{"name":"Curaçao"},
    "cy":{"name":"Kypros"},
    "cz":{"name":"Česká republika"},
    "dk":{"name":"Danmark"},
    "dj":{"name":"جيبوتي"},
    "dm":{"name":"Dominica"},
    "do":{"name":"República Dominicana"},
    "ec":{"name":"Ecuador"},
    "eg":{"name":"مصر"},
    "sv":{"name":"El Salvador"},
    "gq":{"name":"Guinea Ecuatorial"},
    "er":{"name":"إرتريا"},
    "ee":{"name":"Eesti"},
    "et":{"name":"ኢትዮጵያ"},
    "fk":{"name":"Falkland Islands"},
    "fo":{"name":"Føroyar"},
    "fj":{"name":"Fiji"},
    "fi":{"name":"Suomi"},
    "fr":{"name":"France"},
    "gf":{"name":"Guyane"},
    "pf":{"name":"Polynésie française"},
    "tf":{"name":"French Southern Territories"},
    "ga":{"name":"Gabon"},
    "gm":{"name":"Gambia"},
    "ge":{"name":"საქართველო"},
    "de":{"name":"Deutschland"},
    "gh":{"name":"Ghana"},
    "gi":{"name":"Gibraltar"},
    "gr":{"name":"Ελλάς"},
    "gl":{"name":"Kalaallit Nunaat"},
    "gd":{"name":"Grenada"},
    "gp":{"name":"Guadeloupe"},
    "gu":{"name":"Guåhån"},
    "gt":{"name":"Guatemala"},
    "gg":{"name":"Guernsey"},
    "gn":{"name":"Guinée"},
    "gw":{"name":"Guiné-Bissau"},
    "gy":{"name":"Guyana"},
    "ht":{"name":"Haïti"},
    "hm":{"name":"Heard Island and McDonald Islands"},
    "va":{"name":"Holy See (Vatican City State)"},
    "hn":{"name":"Honduras"},
    "hk":{"name":"Hong Kong"},
    "hu":{"name":"Magyarország"},
    "is":{"name":"Ísland"},
    "in":{"name":"भारत"},
    "id":{"name":"Indonesia"},
    "ir":{"name":"ایران"},
    "iq":{"name":"العراق"},
    "ie":{"name":"Éire"},
    "im":{"name":"Isle of Man"},
    "il":{"name":"ישראל"},
    "it":{"name":"Italia"},
    "jm":{"name":"Jamaica"},
    "je":{"name":"Jersey"},
    "jo":{"name":"الأردن"},
    "kz":{"name":"Қазақстан"},
    "ke":{"name":"Kenya"},
    "ki":{"name":"Kiribati"},
    "kp":{"name":"조선민주주의인민공화국"},
    "kw":{"name":"الكويت"},
    "kg":{"name":"Кыргызстан"},
    "la":{"name":"ປະເທດລາວ"},
    "lv":{"name":"Latvija"},
    "lb":{"name":"لبنان"},
    "ls":{"name":"Lesotho"},
    "lr":{"name":"Liberia"},
    "ly":{"name":"ليبيا"},
    "li":{"name":"Liechtenstein"},
    "lt":{"name":"Lietuva"},
    "lu":{"name":"Lëtzebuerg"},
    "mo":{"name":"Macao"},
    "mk":{"name":"Македонија"},
    "mg":{"name":"Madagasikara"},
    "mw":{"name":"Malawi"},
    "my":{"name":"Malaysia"},
    "mv":{"name":"ދިވެހިރާއްޖެ"},
    "ml":{"name":"Mali"},
    "mt":{"name":"Malta"},
    "mh":{"name":"Marshall Islands"},
    "mq":{"name":"Martinique"},
    "mr":{"name":"موريتانيا"},
    "mu":{"name":"Maurice"},
    "yt":{"name":"Mayotte"},
    "mx":{"name":"México"},
    "fm":{"name":"Micronesia, Federated States of"},
    "md":{"name":"Moldova"},
    "mc":{"name":"Monaco"},
    "mn":{"name":"Монгол Улс"},
    "me":{"name":"Crna Gora"},
    "ms":{"name":"Montserrat"},
    "ma":{"name":"المغرب"},
    "mz":{"name":"Moçambique"},
    "mm":{"name":"Myanmar"},
    "na":{"name":"Namibia"},
    "nr":{"name":"Nauru"},
    "np":{"name":"Nepāla"},
    "nl":{"name":"Nederland"},
    "nc":{"name":"Nouvelle-Calédonie"},
    "nz":{"name":"New Zealand"},
    "ni":{"name":"Nicaragua"},
    "ne":{"name":"Niger"},
    "ng":{"name":"Nigeria"},
    "nu":{"name":"Niuē"},
    "nf":{"name":"Norfolk Island"},
    "mp":{"name":"Northern Mariana Islands"},
    "no":{"name":"Norge"},
    "om":{"name":"عُمان"},
    "pk":{"name":"پاکستان"},
    "pw":{"name":"Belau"},
    "ps":{"name":"فلسطين"},
    "pa":{"name":"Panamá"},
    "pg":{"name":"Papua New Guinea"},
    "py":{"name":"Paraguay"},
    "pe":{"name":"Perú"},
    "ph":{"name":"Pilipinas"},
    "pn":{"name":"Pitcairn"},
    "pl":{"name":"Polska"},
    "pt":{"name":"Portugal"},
    "pr":{"name":"Puerto Rico"},
    "qa":{"name":"قطر"},
    "re":{"name":"Réunion"},
    "ro":{"name":"România"},
    "ru":{"name":"Россия"},
    "rw":{"name":"Rwanda"},
    "bl":{"name":"Saint-Barthélemy"},
    "sh":{"name":"Saint Helena, Ascension and Tristan da Cunha"},
    "kn":{"name":"Saint Kitts and Nevis"},
    "lc":{"name":"Saint Lucia"},
    "mf":{"name":"Saint-Martin"},
    "pm":{"name":"Saint-Pierre et Miquelon"},
    "vc":{"name":"Saint Vincent and the Grenadines"},
    "ws":{"name":"Samoa"},
    "sm":{"name":"San Marino"},
    "st":{"name":"São Tomé"},
    "sa":{"name":"المملكة العربية السعودية"},
    "sn":{"name":"Sénégal"},
    "rs":{"name":"Србија"},
    "sc":{"name":"Sesel"},
    "sl":{"name":"Sierra Leone"},
    "sg":{"name":"Singapura"},
    "sx":{"name":"Sint Maarten"},
    "sk":{"name":"Slovensko"},
    "si":{"name":"Slovenija"},
    "sb":{"name":"Solomon Islands"},
    "so":{"name":"Soomaaliya"},
    "za":{"name":"South Africa"},
    "gs":{"name":"South Georgia and the South Sandwich Islands"},
    "ss":{"name":"South Sudan"},
    "es":{"name":"España"},
    "lk":{"name":"ශ්‍රී ලංකාව"},
    "sd":{"name":"السودان"},
    "sr":{"name":"Suriname"},
    "sj":{"name":"Svalbard"},
    "sz":{"name":"Swaziland"},
    "se":{"name":"Sverige"},
    "ch":{"name":"Schweiz"},
    "sy":{"name":"سورية"},
    "tw":{"name":"中華民國"},
    "tj":{"name":"Тоҷикистон"},
    "tz":{"name":"Tanzania, United Republic of"},
    "th":{"name":"เมืองไทย"},
    "tl":{"name":"Timor-Leste"},
    "tg":{"name":"Togo"},
    "tk":{"name":"Tokelau"},
    "to":{"name":"Tonga"},
    "tt":{"name":"Trinidad and Tobago"},
    "tn":{"name":"Tunes"},
    "tr":{"name":"Türkiye"},
    "tm":{"name":"Türkmenistan"},
    "tc":{"name":"Turks and Caicos Islands"},
    "tv":{"name":"Tuvalu"},
    "ug":{"name":"Uganda"},
    "ua":{"name":"Ukraїna"},
    "ae":{"name":"الإمارات العربيّة المتّحدة"},
    "gb":{"name":"United Kingdom"},
    "um":{"name":"United States Minor Outlying Islands"},
    "uy":{"name":"República Oriental del Uruguay"},
    "uz":{"name":"Ўзбекистон"},
    "vu":{"name":"Vanuatu"},
    "ve":{"name":"Venezuela, Bolivarian Republic of"},
    "vn":{"name":"Việt Nam"},
    "vg":{"name":"Virgin Islands, British"},
    "vi":{"name":"Virgin Islands, U.S."},
    "wf":{"name":"Wallis-et-Futuna"},
    "eh":{"name":"Western Sahara"},
    "ye":{"name":"اليمن"},
    "zm":{"name":"Zambia"},
    "zw":{"name":"Zimbabwe"}
  });